upstream auth-service {
    server auth-service:3001;
}

upstream patient-service {
    server patient-service:3002;
}

upstream rdv-service {
    server rdv-service:3003;
}

upstream frontend {
    server frontend:3000;
}

server {
    listen 80;

    # Route vers le Frontend
    location / {
        proxy_pass http://frontend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route vers Auth Service
    location /api/auth/ {
        proxy_pass http://auth-service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route vers Patient Service
    location /api/patients/ {
        proxy_pass http://patient-service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route vers RDV Service
    location /api/rdv/ {
        proxy_pass http://rdv-service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}